"""username_index

Revision ID: 47a6a801b9ea
Revises: 51c3eb4399c0
Create Date: 2022-12-30 13:07:54.307645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '47a6a801b9ea'
down_revision = '51c3eb4399c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
