"""add_file_user_id

Revision ID: 7451b106b93d
Revises: dc575754f077
Create Date: 2023-01-01 12:42:59.284330

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7451b106b93d'
down_revision = 'dc575754f077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False, comment='Связь с пользователем'))
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'user_id')
    # ### end Alembic commands ###
