"""sub_dirs

Revision ID: dc575754f077
Revises: 5729a0ec2513
Create Date: 2022-12-31 07:40:44.885081

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc575754f077'
down_revision = '5729a0ec2513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Может быть родительская директория'))
    op.create_foreign_key(None, 'directory', 'directory', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directory', type_='foreignkey')
    op.drop_column('directory', 'parent_id')
    # ### end Alembic commands ###
