name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        database-name:
        - postgres
        database-password:
        - postgres
        database-user:
        - postgres
        database-host:
        - 127.0.0.1
        database-port:
        - 5432

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        ports:
          - 5432:5432
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.3.1
        python -m poetry config virtualenvs.in-project true
        python -m poetry install
    - name: Lint with flake8 and mypy
      run: |
        python -m poetry run python -m flake8 src/
        python -m poetry run python -m mypy src/
    - name: Test with pytest
      env:
        RW_DSN: postgresql+asyncpg://postgres@127.0.0.1:5432/postgres
        TEST_DSN: postgresql+asyncpg://postgres@127.0.0.1:5432/postgres
        REDIS_DSN: redis://127.0.0.1:6379/1
        SECRET_KEY: 12345
      run: |
        cd src
        pwd
        ls -la
        python -m poetry run python -m pytest
