name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.3.1
        python -m poetry config virtualenvs.in-project true
        python -m poetry install
    - name: Lint with flake8 and mypy
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m poetry run pwd
        python -m poetry run python -m flake8 src/
        python -m poetry run python -m mypy src/
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest
